@"
FROM php:8.2-fpm

RUN apt-get update && apt-get install -y `
    git `
    zip `
    unzip `
    curl `
    libonig-dev `
    libzip-dev `
    && docker-php-ext-install pdo_mysql zip mbstring

WORKDIR /var/www/html

COPY . .

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install

CMD ["php-fpm"]
"@ > Dockerfile

