services:
  app:
    image: php:8.2-fpm
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql-laravel
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: procomsumidor
    ports:
      - 3307:3306   # Cambié el puerto host a 3307 para evitar conflicto
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
